################################################################################
MLI_FILE		= cordova_sms.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-sms
################################################################################
